/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TokenIndexRouteImport } from './routes/token/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as AuthorizeIndexRouteImport } from './routes/authorize/index'
import { Route as ErrorAuthorizationFailureRouteImport } from './routes/error/authorization-failure'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TokenIndexRoute = TokenIndexRouteImport.update({
  id: '/token/',
  path: '/token/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorizeIndexRoute = AuthorizeIndexRouteImport.update({
  id: '/authorize/',
  path: '/authorize/',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorAuthorizationFailureRoute =
  ErrorAuthorizationFailureRouteImport.update({
    id: '/error/authorization-failure',
    path: '/error/authorization-failure',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/error/authorization-failure': typeof ErrorAuthorizationFailureRoute
  '/authorize/': typeof AuthorizeIndexRoute
  '/login/': typeof LoginIndexRoute
  '/token/': typeof TokenIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/error/authorization-failure': typeof ErrorAuthorizationFailureRoute
  '/authorize': typeof AuthorizeIndexRoute
  '/login': typeof LoginIndexRoute
  '/token': typeof TokenIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/error/authorization-failure': typeof ErrorAuthorizationFailureRoute
  '/authorize/': typeof AuthorizeIndexRoute
  '/login/': typeof LoginIndexRoute
  '/token/': typeof TokenIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/error/authorization-failure'
    | '/authorize/'
    | '/login/'
    | '/token/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/error/authorization-failure' | '/authorize' | '/login' | '/token'
  id:
    | '__root__'
    | '/'
    | '/error/authorization-failure'
    | '/authorize/'
    | '/login/'
    | '/token/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ErrorAuthorizationFailureRoute: typeof ErrorAuthorizationFailureRoute
  AuthorizeIndexRoute: typeof AuthorizeIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  TokenIndexRoute: typeof TokenIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/token/': {
      id: '/token/'
      path: '/token'
      fullPath: '/token/'
      preLoaderRoute: typeof TokenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authorize/': {
      id: '/authorize/'
      path: '/authorize'
      fullPath: '/authorize/'
      preLoaderRoute: typeof AuthorizeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error/authorization-failure': {
      id: '/error/authorization-failure'
      path: '/error/authorization-failure'
      fullPath: '/error/authorization-failure'
      preLoaderRoute: typeof ErrorAuthorizationFailureRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ErrorAuthorizationFailureRoute: ErrorAuthorizationFailureRoute,
  AuthorizeIndexRoute: AuthorizeIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  TokenIndexRoute: TokenIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
