/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthorizationFailureRouteImport } from './routes/authorization-failure'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthorizeIndexRouteImport } from './routes/authorize/index'

const AuthorizationFailureRoute = AuthorizationFailureRouteImport.update({
  id: '/authorization-failure',
  path: '/authorization-failure',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorizeIndexRoute = AuthorizeIndexRouteImport.update({
  id: '/authorize/',
  path: '/authorize/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/authorization-failure': typeof AuthorizationFailureRoute
  '/authorize/': typeof AuthorizeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/authorization-failure': typeof AuthorizationFailureRoute
  '/authorize': typeof AuthorizeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/authorization-failure': typeof AuthorizationFailureRoute
  '/authorize/': typeof AuthorizeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/authorization-failure' | '/authorize/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/authorization-failure' | '/authorize'
  id: '__root__' | '/' | '/authorization-failure' | '/authorize/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthorizationFailureRoute: typeof AuthorizationFailureRoute
  AuthorizeIndexRoute: typeof AuthorizeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/authorization-failure': {
      id: '/authorization-failure'
      path: '/authorization-failure'
      fullPath: '/authorization-failure'
      preLoaderRoute: typeof AuthorizationFailureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authorize/': {
      id: '/authorize/'
      path: '/authorize'
      fullPath: '/authorize/'
      preLoaderRoute: typeof AuthorizeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthorizationFailureRoute: AuthorizationFailureRoute,
  AuthorizeIndexRoute: AuthorizeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
